// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "grqphical",
            "url": "https://github.com/grqphical/postal-code-lookup"
        },
        "license": {
            "name": "GNU Public License Version 3.0",
            "url": "https://github.com/grqphical/postal-code-lookup/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "produces": [
                    "text/plain"
                ],
                "summary": "check the status of the API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": ""
                        }
                    }
                }
            }
        },
        "/postal-code/{postalCode}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "extracts information about a postal code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Postal Code to extract info from",
                        "name": "postalCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/lookup.PostalCode"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.HttpError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "lookup.PostalCode": {
            "description": "Contains the extracted data from the given postal code",
            "type": "object",
            "properties": {
                "businessReply": {
                    "description": "is this code used as part of the Business Reply system",
                    "type": "boolean"
                },
                "governmentBuilding": {
                    "description": "does the postal code belong to a building owned by the Canadian government",
                    "type": "boolean"
                },
                "municipality": {
                    "description": "what municipality the postal code is located in",
                    "type": "string"
                },
                "postOffice": {
                    "description": "is this code a Canada Post post office",
                    "type": "boolean"
                },
                "province": {
                    "description": "what province/territory the postal code is in",
                    "type": "string"
                },
                "regionalDistrubutionCentre": {
                    "description": "is the postal code a Canada post distribution centre",
                    "type": "boolean"
                },
                "subdivision": {
                    "description": "for the bigger provinces, which area of the province is it in",
                    "type": "string"
                },
                "urban": {
                    "description": "whether or not the postal code is in an urban center",
                    "type": "boolean"
                }
            }
        },
        "routes.HttpError": {
            "description": "JSON object returned whenever an error occurs",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Canadian Postal Code Lookup API",
	Description:      "An API to extract information about Canadian postal codes",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
